### ISSUE TITLE
Can't parse single-array system

### ISSUE THREAD

**Issue by CodeCasterNL** [pyrocumulus/pvoutput.net#111]
`System.GetOwnSystemAsync()` throws:

> 'Invalid description 'null' for enum Orientation

SecondaryOrientation is the string `"null"`, because I don't have a secondary array for that system.

https://github.com/pyrocumulus/pvoutput.net/blob/d8077871d2943a287c39d92416dc93c334118291/src/PVOutput.Net/Objects/Modules/Readers/SystemObjectStringReader.cs#L46

**Comment by pyrocumulus** [comment]
Hmm strange.

I also have a single array system and while testing I've never had this issue. I can't remember 'null' literals coming back from the api before. Perhaps the output has changed, or I've made an error when implementing that secondary array orientation (it's a somewhat recent addition).

I'll look into it, shouldn't be hard to find and fix. Thanks for reporting!

**Comment by pyrocumulus** [comment]
Apparently their response has changed a bit, in case of that secondary array. It's actually sending back that literal value instead of an empty string as before.
