### ISSUE TITLE
Add interfaces to enable unit testing

### ISSUE THREAD

**Issue by CodeCasterNL** [pyrocumulus/pvoutput.net#64]
Hi @pyrocumulus, nice library, I'm using it in an upcoming Windows Service that syncs GoodWe API to PVOutput. Somewhere in that code, I have a class that wraps your `PVOutputClient` for configuration and DI purposes, and it has a property:

    public PVOutputClient ApiClient { get; }

Now I want to test that my code calls your code, without actually calling your code, it being test data and all which I don't want to be sent to PVOutput. 

Could you consider interfacing the `PVOutputClient` and its services, so it can be mocked for unit tests?

**Comment by pyrocumulus** [comment]
First of all, thank you for the kind words! It's nice to hear you are using it, I always hoped it would be useful to someone someday👍🏻

About your feature request, no problem. I understand that you need it for unit testing, it's how I use it myself as well. Until now I never looked at my library from an outside unit test standpoint.

Thanks for the PR as well, I'll review it the coming days and integrate it 🙂

**Comment by pyrocumulus** [comment]
The changes have been committed to `develop`. Planning on releasing 0.9.1 tonight.
