### ISSUE TITLE
pvoutput deprecated addbatchoutput

### ISSUE THREAD

**Issue by jwillemsen** [pyrocumulus/pvoutput.net#75]
I found recently that pvoutput has deprecated the addbatchoutput API, batching is now part of addoutput, but batching is only available for donations mode, see https://github.com/jwillemsen/saj_collector/issues/34. It looks this project needs to be updated because it uses addbatchoutput.jsp as far as I can tell.

**Comment by pyrocumulus** [comment]
Thank you for taking the time to let me (and others) know that PVOutput has changed this in their api. I do not use batching myself so otherwise this could have gone unnoticed quite easily.

I'll make arrangements to update my library as well.

Thanks again!
